In [ ]:
import pandas as pd

df_orders = pd.read_csv('./data/orders.csv')
df_customers = pd.read_csv('./data/customers.csv')
df_sales = pd.read_csv('./data/sales.csv')

In [ ]:
pd.concat([df_customers,df])

,customer_id,customer_name,email,city,state,customer_segment,acquisition_channel,loyalty_tier,signup_date,order_id,...,region,sales_channel,product,category,quantity,unit_price,discount_pct,unit_cost,payment_method,returned
0,CUST-0001,Morgan Rodriguez,customer001@example.com,Seattle,WA,Consumer,Referral,Silver,2022-08-13,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,CUST-0002,Rowan Johnson,customer002@example.com,Miami,FL,Consumer,Paid Search,Gold,2022-07-12,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,CUST-0003,Emerson Rodriguez,customer003@example.com,Atlanta,GA,Enterprise,Referral,Gold,2024-10-20,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,CUST-0004,Taylor Davis,customer004@example.com,Miami,FL,Small Business,Social Media,Gold,2023-04-01,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,CUST-0005,Cameron Jones,customer005@example.com,Miami,FL,Small Business,Referral,Silver,2025-02-03,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
498,CUST-0037,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ORD-00499,...,South,Retail,Keyboard,Accessories,2.0,70.16,0.10,52.20,Bank Transfer,False
499,CUST-0054,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ORD-00500,...,North,Retail,Desk Chair,Furniture,5.0,233.04,0.10,170.97,Cash,False
500,CUST-0060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ORD-00013,...,North,Wholesale,Pen Set,Office Supplies,2.0,11.33,0.00,9.20,Bank Transfer,False
501,CUST-0035,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ORD-00046,...,South,Online,Webcam,Electronics,2.0,82.53,0.00,53.06,PayPal,False
502,CUST-0023,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,ORD-00102,...,Central,Retail,Desk Chair,Furniture,1.0,258.16,0.15,128.86,Credit Card,False

In [5]:

# Compile DataFrames into a list
dfs = [df_orders, df_customers, df_sales]

df1_indexed = df_orders.set_index('customer_id')
df2_indexed = df_customers.set_index('customer_id')
df3_indexed = df_sales.set_index('customer_id')

df_joined = df1_indexed.join([df2_indexed, df3_indexed], how='outer')

df_joined.head(10)

,order_id_x,shipping_status,shipping_method,carrier,warehouse,shipped_date,delivery_date,shipping_cost,tracking_number,customer_name,...,region,sales_channel,product,category,quantity,unit_price,discount_pct,unit_cost,payment_method,returned
customer_id,,,,,,,,,,,,,,,,,,,,,
CUST-0001,ORD-00075,Delivered,Standard,Regional Courier,WH-East,2025-06-13,2025-06-16,18.96,TRK3230502775,Morgan Rodriguez,...,Central,Retail,Desk Chair,Furniture,10,233.07,0.00,154.58,Cash,False
CUST-0001,ORD-00075,Delivered,Standard,Regional Courier,WH-East,2025-06-13,2025-06-16,18.96,TRK3230502775,Morgan Rodriguez,...,South,Wholesale,Webcam,Electronics,2,94.32,0.00,51.41,Credit Card,False
CUST-0001,ORD-00075,Delivered,Standard,Regional Courier,WH-East,2025-06-13,2025-06-16,18.96,TRK3230502775,Morgan Rodriguez,...,West,Retail,Standing Desk,Furniture,3,531.40,0.10,385.76,Credit Card,False
CUST-0001,ORD-00075,Delivered,Standard,Regional Courier,WH-East,2025-06-13,2025-06-16,18.96,TRK3230502775,Morgan Rodriguez,...,East,Online,Mouse,Accessories,1,35.17,0.00,24.16,Cash,False
CUST-0001,ORD-00075,Delivered,Standard,Regional Courier,WH-East,2025-06-13,2025-06-16,18.96,TRK3230502775,Morgan Rodriguez,...,Central,Retail,Keyboard,Accessories,4,73.74,0.00,41.23,Credit Card,False
CUST-0001,ORD-00075,Delivered,Standard,Regional Courier,WH-East,2025-06-13,2025-06-16,18.96,TRK3230502775,Morgan Rodriguez,...,East,Wholesale,Notebook,Office Supplies,8,5.86,0.15,4.12,PayPal,False
CUST-0001,ORD-00075,Delivered,Standard,Regional Courier,WH-East,2025-06-13,2025-06-16,18.96,TRK3230502775,Morgan Rodriguez,...,West,Online,Webcam,Electronics,1,90.38,0.00,55.30,PayPal,False
CUST-0001,ORD-00194,Cancelled,Express,UPS,WH-South,NaN,NaN,14.37,TRK5945936770,Morgan Rodriguez,...,Central,Retail,Desk Chair,Furniture,10,233.07,0.00,154.58,Cash,False
CUST-0001,ORD-00194,Cancelled,Express,UPS,WH-South,NaN,NaN,14.37,TRK5945936770,Morgan Rodriguez,...,South,Wholesale,Webcam,Electronics,2,94.32,0.00,51.41,Credit Card,False
CUST-0001,ORD-00194,Cancelled,Express,UPS,WH-South,NaN,NaN,14.37,TRK5945936770,Morgan Rodriguez,...,West,Retail,Standing Desk,Furniture,3,531.40,0.10,385.76,Credit Card,False